CREATE OR REPLACE WORLD_CITY_VIEW AS 
  SELECT
	WCN.ID,
	WCN.NAME,
	WCY.CONTINENT,
	WCY.NAME AS NATION,
	WCN.DISTRICT,
	WCN.POPULATION,
	CTL.LANGUAGE 
FROM
	WORLD_CITY WCN
	INNER JOIN WORLD_COUNTRY WCY ON WCN.COUNTRY_CODE = WCY.CODE
	INNER JOIN (
	SELECT
		WL.COUNTRY_CODE,
	CASE
			
			WHEN ( UM.OFPERCENTAGE - COALESCE( OM.OTPERCENTAGE, 0 ) ) >= 35 THEN
			UM.OFLANGUAGE ELSE COALESCE( OM.OTLANGUAGE, UM.OFLANGUAGE ) 
		END AS LANGUAGE 
	FROM
		WORLD_LANGUAGE WL
		LEFT JOIN (
		SELECT
			AL.COUNTRY_CODE,
			AL.LANGUAGE AS OTLANGUAGE,
			AL.PERCENTAGE AS OTPERCENTAGE,
			ROW_NUMBER ( ) OVER ( PARTITION BY COUNTRY_CODE ORDER BY PERCENTAGE DESC ) AS RNK 
		FROM
			WORLD_LANGUAGE AL 
		WHERE
			AL.DELETE_FLG = 'visible' 
			AND AL.IS_OFFICIAL = 'True' 
		) OM ON OM.COUNTRY_CODE = WL.COUNTRY_CODE 
		AND OM.RNK = 1
		LEFT JOIN (
		SELECT
			AL.COUNTRY_CODE,
			AL.LANGUAGE AS OFLANGUAGE,
			AL.PERCENTAGE AS OFPERCENTAGE,
			ROW_NUMBER ( ) OVER ( PARTITION BY COUNTRY_CODE ORDER BY PERCENTAGE DESC ) AS RNK 
		FROM
			WORLD_LANGUAGE AL 
		WHERE
			AL.DELETE_FLG = 'visible' 
			AND AL.IS_OFFICIAL = 'False' 
		) UM ON UM.COUNTRY_CODE = WL.COUNTRY_CODE 
		AND UM.RNK = 1 
	GROUP BY
		WL.COUNTRY_CODE,
		UM.OFLANGUAGE,
		OM.OTLANGUAGE,
		OM.OTPERCENTAGE,
		UM.OFPERCENTAGE 
	) CTL ON CTL.COUNTRY_CODE = WCN.COUNTRY_CODE 
WHERE
	WCN.DELETE_FLG = 'visible' 
ORDER BY
	WCN.ID WITH READ ONLY;